#!/bin/sh

if [ "$1" = clean ] ; then
    make maintainer-clean
    rm resid unix builders/Makefile.am libsidplay/unix/sidint.h builders/hardsid-builder/unix/config.h
    rm -rf builders/hardsid-builder/autom4te.cache/ builders/hardsid-builder/src/.deps/
    for f in Makefile.in Makefile configure aclocal.m4 compile config.sub depcomp install-sh ltmain.sh missing config.log config.status libtool config.guess stamp-h1 config.h.in ; do
	find . -name $f -delete
    done
    find . -name '*~' -delete
    exit
fi

set -e

pwd=`pwd`
resid="resid-0.16"
dirs="libsidplay libsidutils builders/resid-builder"

test ! -r "resid" && ln -sf "$resid" "resid"
test ! -r "unix" && ln -sf libsidplay/unix unix

echo 'SUBDIRS = resid-builder' > builders/Makefile.am
if [ "$1" = hardsid ] ; then
    shift
    echo 'if HARDSID' >> builders/Makefile.am
    echo 'SUBDIRS += hardsid-builder' >> builders/Makefile.am
    echo 'endif' >> builders/Makefile.am
    dirs="$dirs builders/hardsid-builder"
fi

for d in $dirs; do
    cd "$pwd/$d"
    echo
    echo "Bootstrapping $d..."
    if ! ./bootstrap; then
	echo
	echo "!!! bootstrap $d failed !!!"
	exit
    fi
done

cd "$pwd/resid"
echo
echo "Bootstrapping resid..."
libtoolize --force --install
aclocal --force
automake --force --add-missing --copy
autoconf --force

cd "$pwd"
echo
echo "Bootstrapping sidplay-libs..."
aclocal --force
automake --force --add-missing --copy
autoconf --force
./configure
make "$@"
